{!! Html::script('frontend/plugins/jquery-1.12.4.min.js') !!}
{!! Html::script('frontend/plugins/popper.min.js') !!}
{!! Html::script('frontend/plugins/owl-carousel/owl.carousel.min.js') !!}
{!! Html::script('frontend/plugins/bootstrap4/js/bootstrap.min.js') !!}
{!! Html::script('frontend/plugins/imagesloaded.pkgd.min.js') !!}
{!! Html::script('frontend/plugins/masonry.pkgd.min.js') !!}
{!! Html::script('frontend/plugins/isotope.pkgd.min.js') !!}
{!! Html::script('frontend/plugins/jquery.matchHeight-min.js') !!}
{!! Html::script('frontend/plugins/slick/slick/slick.min.js') !!}
{!! Html::script('frontend/plugins/jquery-bar-rating/dist/jquery.barrating.min.js') !!}
{!! Html::script('frontend/plugins/slick-animation.min.js') !!}
{!! Html::script('frontend/plugins/lightGallery-master/dist/js/lightgallery-all.min.js') !!}
{!! Html::script('frontend/plugins/jquery-ui/jquery-ui.min.js') !!}
{!! Html::script('frontend/plugins/sticky-sidebar/dist/sticky-sidebar.min.js') !!}
{!! Html::script('frontend/plugins/jquery.slimscroll.min.js') !!}
{!! Html::script('frontend/plugins/select2/dist/js/select2.full.min.js') !!}
{!! Html::script('frontend/plugins/gmap3.min.js') !!}
<!-- custom scripts-->
{!! Html::script('frontend/js/main.js') !!}
{!! Html::script('frontend/js/front.js') !!}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxflHHc5FlDVI-J71pO7hM1QJNW1dRp4U&amp;region=GB"></script>